### ISSUE TITLE
Add Dijsktra Algorithm

### ISSUE THREAD

**Issue by anaghamittal** [codezonediitj/pydatastructs#153]
#### Description of the problem
Competitive programming also needs concepts related to greedy algorithms, hence it is a necessary section that should be added

#### Example of the problem
Videos and lectures related to greedy algorithms such as dijkstra can be added

**Comment by czgdp1807** [comment]
Hi @anaghamittal 
The idea is quite abstract. We can work on concrete algorithms like you have dijkstra algorithm can go to https://github.com/codezonediitj/pydatastructs/blob/master/pydatastructs/graphs/algorithms.py
Since, we don't have priority queue right now, so first that should be added. See, #131

**Comment by Tawishi** [comment]
I would like to take up this issue.

**Comment by czgdp1807** [comment]
Priority Queue is now added, so you can work Dijsktra algorithm. See plan of action at https://github.com/codezonediitj/pydatastructs/wiki/Plan-of-Action-for-the-Projects

**Comment by Kiran-Venkatesh** [comment]
I would like to take up this issue.

**Comment by czgdp1807** [comment]
If you have gone through the README and our policies in wiki then please feel free to raise a PR.

**Comment by Kiran-Venkatesh** [comment]
finished changes in coding by adding dijsktra algorithm,how to add,commit and raise a PR?
